secrets:
  config:
    file: secrets/config.php

services:
  booking:
    restart: unless-stopped
    image: booking:latest
    build:
      context: .
    secrets:
      - source: config
        target: /var/www/config.php
    volumes:
      - ./logs:/var/www/logs:rw
